'

!final function $httpError($ERROR_CODE,$ERROR_DESCR)
	!return $errorResponse("HTTP",$ERROR_CODE,$ERROR_DESCR)
!endfunction

' HTTP Status Codes
!final function $http100() !return $statusResponse("HTTP","100","Continue")
!final function $http101() !return $statusResponse("HTTP","101","Switching Protocols")
!final function $http102() !return $statusResponse("HTTP","102","Processing")
'old deprecated 100 status
!$http100 =	$statusResponse("HTTP","100","Continue")
!$http101 =	$statusResponse("HTTP","101","Switching Protocols")
!$http102 =	$statusResponse("HTTP","102","Processing")

!final function $http200() !return $statusResponse("HTTP","200","OK")
!final function $http201() !return $statusResponse("HTTP","201","Created")
!final function $http202() !return $statusResponse("HTTP","202","Accepted")
!final function $http203() !return $statusResponse("HTTP","203","Non-Authoritative Information")
!final function $http204() !return $statusResponse("HTTP","204","No Content")
!final function $http205() !return $statusResponse("HTTP","205","Reset Content")
!final function $http206() !return $statusResponse("HTTP","206","Partial Content")

'old deprecated 2xx status
!$http200 = $statusResponse("HTTP","200","OK")
!$http201 = $statusResponse("HTTP","201","Created")
!$http202 =	$statusResponse("HTTP","202","Accepted")
!$http203 =	$statusResponse("HTTP","203","Non-Authoritative Information")
!$http204 = $statusResponse("HTTP","204","No Content")
!$http205 =	$statusResponse("HTTP","205","Reset Content")
!$http206 =	$statusResponse("HTTP","206","Partial Content")

' 300
!final function $http301() !return $statusResponse("HTTP","301","Moved Permanently")
!final function $http302() !return $statusResponse("HTTP","302","Found (Moved Temporarily)")
!final function $http303() !return $statusResponse("HTTP","303","See Other")
!final function $http304() !return $statusResponse("HTTP","304","Not Modified")
!final function $http305() !return $statusResponse("HTTP","305","Use Proxy)
!final function $http306() !return $statusResponse("HTTP","306","Switch Proxy")
!final function $http307() !return $statusResponse("HTTP","307","Temporary Redirect")
!final function $http308() !return $statusResponse("HTTP","308","Permanent Redirect")
'old deprecated 3xx status
!$http301 =	$httpError("301","Moved Permanently")
!$http302 =	$httpError("302","Found (Moved Temporarily)")
!$http303 =	$httpError("303","See Other")
!$http304 =	$httpError("304","Not Modified")
!$http305 =	$httpError("305","Use Proxy")
!$http306 =	$httpError("306","Switch Proxy")
!$http307 =	$httpError("307","Temporary Redirect")
!$http308 =	$httpError("308","Permanent Redirect")

' Client error
!final function $http400() !return $statusResponse("HTTP","400","Bad Request")
!final function $http401() !return $statusResponse("HTTP","401","Unauthorized")
!final function $http403() !return $statusResponse("HTTP","403","Forbidden")
!final function $http404() !return $statusResponse("HTTP","404","Not Found")
!final function $http405() !return $statusResponse("HTTP","405","Method Not Allowed")
!final function $http406() !return $statusResponse("HTTP","406","Not Acceptable")
!final function $http408() !return $statusResponse("HTTP","408","Request Timeout")
!final function $http409() !return $statusResponse("HTTP","409","Conflict")
!final function $http410() !return $statusResponse("HTTP","410","Gone")
!final function $http412() !return $statusResponse("HTTP","412","Precondition Failed")
!final function $http413() !return $statusResponse("HTTP","413","Payload Too Large")
!final function $http414() !return $statusResponse("HTTP","414","URI Too Long")
!final function $http415() !return $statusResponse("HTTP","415","Unsupported Media Type")
!final function $http416() !return $statusResponse("HTTP","416","Range Not Satisfiable")
!final function $http417() !return $statusResponse("HTTP","417","Expectation Failed")
!final function $http420() !return $statusResponse("HTTP","420","Policy Not Fulfilled")
!final function $http421() !return $statusResponse("HTTP","421","Misdirected Request")
!final function $http422() !return $statusResponse("HTTP","422","Unprocessable Entity")
!final function $http423() !return $statusResponse("HTTP","423","Locked")
!final function $http424() !return $statusResponse("HTTP","424","Failed Dependency")
!final function $http425() !return $statusResponse("HTTP","425","Too Early")
!final function $http426() !return $statusResponse("HTTP","426","Upgrade Required")
!final function $http428() !return $statusResponse("HTTP","428","Precondition Required")
!final function $http429() !return $statusResponse("HTTP","429","Too Many Requests")
!final function $http431() !return $statusResponse("HTTP","431","Request Header Fields Too Large")
!final function $http444() !return $statusResponse("HTTP","444","No Response")
!final function $http451() !return $statusResponse("HTTP","451","Unavailable For Legal Reasons")
'old deprecated 4xx status
!$http400 = $httpError("400","Bad Request")
!$http401 = $httpError("401","Unauthorized")
!$http403 = $httpError("403","Forbidden")
!$http404 = $httpError("404","Not Found")
!$http405 = $httpError("405","Method Not Allowed")
!$http406 = $httpError("406","Not Acceptable")
!$http408 =	$httpError("408","Request Timeout")
!$http409 = $httpError("409","Conflict")
!$http410 = $httpError("410","Gone")
!$http412 = $httpError("412","Precondition Failed")
!$http413 = $httpError("413","Payload Too Large")
!$http414 = $httpError("414","URI Too Long")
!$http415 = $httpError("415","Unsupported Media Type")
!$http416 = $httpError("416","Range Not Satisfiable")
!$http417 = $httpError("417","Expectation Failed")
!$http420 = $httpError("420","Policy Not Fulfilled")
!$http421 = $httpError("421","Misdirected Request")
!$http422 = $httpError("422","Unprocessable Entity")
!$http423 = $httpError("423","Locked")
!$http424 = $httpError("424","Failed Dependency")
!$http425 = $httpError("425","Too Early")
!$http426 = $httpError("426","Upgrade Required")
!$http428 = $httpError("428","Precondition Required")
!$http429 = $httpError("429","Too Many Requests")
!$http431 = $httpError("431","Request Header Fields Too Large")
!$http444 = $httpError("444","No Response")
!$http451 = $httpError("451","Unavailable For Legal Reasons")

' Server error
!final function $http500() !return $statusResponse("HTTP","500","Internal Server Error")
!final function $http501() !return $statusResponse("HTTP","501","Not Implemented")
!final function $http502() !return $statusResponse("HTTP","502","Bad Gateway")
!final function $http503() !return $statusResponse("HTTP","503","Service Unavailable")
!final function $http504() !return $statusResponse("HTTP","504","Gateway Timeout")
!final function $http505() !return $statusResponse("HTTP","505","HTTP Version not supported")
!final function $http506() !return $statusResponse("HTTP","506","Variant also Negotiates")
!final function $http507() !return $statusResponse("HTTP","507","Insufficient Storage")
!final function $http508() !return $statusResponse("HTTP","508","Loop Detected")
!final function $http509() !return $statusResponse("HTTP","509","Bandwidth Limit Exceeded")
!final function $http510() !return $statusResponse("HTTP","510","Not Extended")
!final function $http511() !return $statusResponse("HTTP","511","Network Authentication Required"")
'old deprecated 5xx status
!$http500 = $httpError("500","Internal Server Error")
!$http501 = $httpError("501","Not Implemented")
!$http502 = $httpError("502","Bad Gateway")
!$http503 = $httpError("503","Service Unavailable")
!$http504 = $httpError("504","Gateway Timeout")
!$http505 = $httpError("505","HTTP Version not supported")
!$http506 = $httpError("506","Variant also Negotiates")
!$http507 = $httpError("507","Insufficient Storage")
!$http505 = $httpError("508","Loop Detected")
!$http509 = $httpError("509","Bandwidth Limit Exceeded")
!$http510 = $httpError("510","Not Extended")
!$http511 = $httpError("511","Network Authentication Required")
