# Name of the application
# Usually this is used as Name in a component "name" as alias <<domainColor>>,
# as well as the name of the exported folder, beware of any special characters.
# You may customize by: component "customLabel" as customAlias <<domainColor>>
application: newApplication
# customLabel defines the visual name of an component
#    e.g. customLabel foo would result in component "foo" as
customLabel: <$demo> New Application \n with CR
# The name of the alias that can be used to connect to a component, default is applicationName. to lower case and no special characters
# e.g. newApplication -> newapplication
customAlias:
# the type of application (default is application which means component for component diagrams and participant for sequences):
#   values:  application or component, database, springboot, archive, zip, user, address_book, email, folder, documents, jenkins
systemType: application
# what kind of interface HTTPS::XML, HTTP::JSON, SOAP::HTTP, SOAP (as synonym for (HTTP and JMS Endpoints))
#integrationType: REST::JSON
# Domain values:
#    BiPRO(authentifizierung, suche, uebermittlung, bestand, taa, risikodaten, spezifisches),
#    SID(customer, integration, resource, financial, external),
#    or own Domains that additionally need to be added to the file default.skin
#
domainColor: uebermittlung
# sequence diagram position, default=0, negative numbers move the participant more left and positive numbers move a participant more right
orderPrio: 1000
# Whether or not this application should automatically linked to another component such as the own db
linkToComponent: Filesystem
linkToCustomAlias:
services:
    # services and their interface e.g. for SOAP: Service: [method] or for REST: api/path: [interface]
    # Service calls are generated as $<application>_<service>_<interface>() except for EMPTY which results in $<application>_<interface>()
    REST::JSON:
        EMPTY: [newService->ESB_TDB_toBeDefined->Solr_solr_partner_select,newService2]
        serviceLess/serviceMore: [intMore/withCallStack->Filesystem_readFile]
    SOAP:
        serviceMore.andMore : [interface]
        serviceLess.intMore.intMore2: [noCallStack]
    DB:
        EMPTY: [access]