@startuml
sprite $tibco [48x48/16z] {
jTHNOYCX40JG9iUg-zzs7HZCI3IQhtssSf63x6p8zLkEJXwPrC4_wDdA1ww1x-gn5TEeo8HU8eAAribSPLUfGIHx9xPXDAeYo4Xk1GxnMiXUkHMeLC6Hz1Zl
POc7k0NPCeScam5LFeyob_3G-UH0biG9CZYgYe34lUtugVecbMH8NF2XzrtYRo7mnikthCVTRsyIxwfywrfyj1fNzQj3qFek_VUby9KHyTpKCGSmsz22rlqi
erw_prpPjmwYI1h5tA6ZTt3NTkhRoBGlkxdYC9BucCyourPTHzppus2dEH6D3_coLZiTpaHVu-rk7RHwsbLjDeietqoVtqgdfewbGHu70RDHRMvcFsTQueex
KEL4J5odSiRb48VyyRZ56tLTBgRUlqayYEzNRLjDdRlZyB9Y5ZoeRxTRMiTV0oF3IC3BuJYlreTmAzruWfVhkSvtHrwMVdqeFCgoopog_pMUPUTu0YyQ1prT
vIHq9Mtb0vixRk4MvPaDgTHIaZUo-m8
}

!define FA_TIBCO(_alias) ENTITY(rectangle,black,tibco,_alias,FA_TIBCO)
!define FA_TIBCO(_alias, _label) ENTITY(rectangle,black,tibco,_label, _alias,FA_TIBCO)
!define FA_TIBCO(_alias, _label, _shape) ENTITY(_shape,black,tibco,_label, _alias,FA_TIBCO)
!define FA_TIBCO(_alias, _label, _shape, _color) ENTITY(_shape,_color,tibco,_label, _alias,FA_TIBCO)
skinparam folderBackgroundColor<<FA_TIBCO>> white
@enduml
